### ISSUE TITLE
Asking for the requirement.txt

### ISSUE THREAD

**Issue by CaoYongwang** [PhaelIshall/SemEval2020-Code#2]
Could you please provide the requirement.txt file?I want to run your code, but the environment has not been very correct, thank you very much.

**Comment by PhaelIshall** [comment]
@CaoYongwang Hi, you can now find the requirements.txt file [here](https://github.com/PhaelIshall/SemEval2020-Code/blob/master/requirements.txt)

I also added instructions in the README file for the python version (3.6)
